In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt 
import re
from cycler import cycler 
import os
import numpy as np

pd.set_option('display.max_colwidth', -1)

In [5]:
df = pd.read_csv("treaty1celestial.csv")

In [7]:
df['Date_of_Notification/Deposit'] = pd.to_datetime(df['Date_of_Notification/Deposit'], format='%d/%m/%Y')

In [14]:
df = df.sort_values(by='Date_of_Notification/Deposit',ascending=True)

In [19]:
df.drop_duplicates(subset=None, keep='last', inplace=True)

In [21]:
df.to_csv("CelestialTreaty.csv" , index=False)

In [23]:
df['Action'].unique()

array(['Accession', 'Signature', 'Declaration', 'Ratification',
       'Succession', 'Territorial application'], dtype=object)

In [27]:
df[df['Action'] == 'Declaration']

,Participant,Action,Date_of_Notification/Deposit,Date_of_Effect
147,Republic of Korea,Declaration,1967-01-27,NaN

In [8]:
spaceTreaties = pd.read_csv('SpaceTreaties.csv')

In [9]:
spaceTreaties.shape

(211, 6)

In [10]:
dropNAtreaties = spaceTreaties.dropna(thresh=2)

In [11]:
dropNAtreaties.shape

(145, 6)

In [14]:
dropNAtreaties.Countries.unique()

array(['Afghanistan', 'Algeria', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada',
       'Central African', 'Chile', 'China', 'Colombia', 'Costa Rica',
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'North Korea',
       'Democratic Republic of the Congo', 'Denmark',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Lao People’s',
       'Lebanon', 'Lesotho', 'Libya', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malaysia', 'Maldives', 'Mali',
       'Malta', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Myanmar', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Rwanda',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'South Africa', 'Spain', 'Sri Lanka',
       'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Venezuela',
       'Viet Nam', 'Yemen', 'Zambia'], dtype=object)

In [13]:
dropNAtreaties.Countries.replace({'Bolivia (Plurinational':'Bolivia', 
                                  'Democratic People’s':'North Korea',
                                  'Democratic Republic':'Democratic Republic of the Congo', 
                                  'Iran (Islamic':'Iran', 'Saint Vincent and':'Saint Vincent and the Grenadines', 
                                  'United Kingdom of':'United Kingdom', 
                                  'United Republic of':'Egypt', 
                                  'United States of':'United States',
                                  'Venezuela (Bolivarian':'Venezuela'} , inplace=True)

/Users/TekendraMBP/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/core/generic.py:5886: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [22]:
#Countries	OST	ARRA	LIAB	REG	MOON

dropNAtreaties.MOON.unique()

array([nan, 'R', 'S'], dtype=object)

In [24]:
dropNAtreaties.fillna('NA', inplace=True)

/Users/TekendraMBP/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/core/frame.py:3790: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [25]:
dropNAtreaties

                  Countries OST ARRA LIAB REG MOON
0    Afghanistan             R   NA   NA   NA  NA
2    Algeria                 R   NA   R    R   NA
5    Antigua and Barbuda     R   R    R    R   NA
6    Argentina               R   R    R    R   NA
7    Armenia                 NA  NA   NA   R   R
8    Australia               R   R    R    R   R
9    Austria                 R   R    R    R   R
10   Azerbaijan              R   NA   NA   NA  NA
11   Bahamas                 R   R    NA   NA  NA
13   Bangladesh              R   NA   NA   NA  NA
14   Barbados                R   R    NA   NA  NA
15   Belarus                 R   R    R    R   NA
16   Belgium                 R   R    R    R   R
18   Benin                   R   NA   R    NA  NA
20   Bolivia                 S   S    NA   NA  NA
22   Bosnia and Herzegovina  NA  R    R    NA  NA
23   Botswana                S   R    R    NA  NA
24   Brazil                  R   R    R    R   NA
26   Bulgaria                R   R    R    R   NA
27   Burkina Faso            R   NA   NA   NA  NA
28   Burundi                 S   NA   S    S   NA
29   Cambodia                NA  NA   S    NA  NA
30   Cameroon                S   R    NA   NA  NA
31   Canada                  R   R    R    R   NA
33   Central African         S   NA   S    NA  NA
36   Chile                   R   R    R    R   R
37   China                   R   R    R    R   NA
38   Colombia                S   S    R    R   NA
42   Costa Rica              NA  S    S    R   NA
44   Croatia                 NA  R    R    NA  NA
..       ...                 .. ..   ..    ..  ..
160  Serbia                  S   R    R    R   NA
161  Seychelles              R   R    R    R   NA
162  Sierra Leone            R   S    S    NA  NA
163  Singapore               R   R    R    S   NA
164  Slovakia                R   R    R    R   NA
165  Slovenia                NA  R    R    NA  NA
167  South Africa            R   R    R    R   NA
169  Spain                   R   R    R    R   NA
170  Sri Lanka               R   NA   R    NA  NA
173  Swaziland               NA  R    NA   NA  NA
174  Sweden                  R   R    R    R   NA
175  Switzerland             R   R    R    R   NA
176  Syrian Arab Republic    R   R    R    NA  NA
178  Thailand                R   R    NA   NA  NA
183  Togo                    R   NA   R    NA  NA
184  Tonga                   R   R    NA   NA  NA
185  Trinidad and Tobago     S   NA   R    NA  NA
186  Tunisia                 R   R    R    NA  NA
187  Turkey                  R   R    R    R   R
190  Uganda                  R   NA   NA   NA  NA
191  Ukraine                 R   R    R    R   NA
192  United Arab Emirates    R   NA   R    R   NA
193  United Kingdom          R   R    R    R   NA
196  Egypt                   NA  NA   S    NA  NA
198  United States           R   R    R    R   NA
200  Uruguay                 R   R    R    R   R
203  Venezuela               R   S    R    R   R
205  Viet Nam                R   S    NA   NA  NA
206  Yemen                   R   S    NA   NA  NA
207  Zambia                  R   R    R    NA  NA

[145 rows x 6 columns]

In [26]:
dropNAtreaties.to_csv('spaceTreatiesCleaned.csv', index=False)